### ISSUE TITLE
Removing all highlights in open buffer at once

### ISSUE THREAD

**Issue by lcrockett** [kdav5758/HighStr.nvim#2]
Just for future reference and anyone wondering how to achieve removing all highlights in the open buffer in one go, see below for global function snippet.

```lua
function _G.highstr_highlight_remove_all()
  local api = vim.api
  local buffer_current_number = api.nvim_eval([[bufnr('%')]])
  local line_last = vim.fn.line('$')

  api.nvim_buf_clear_namespace(buffer_current_number, 0, 1 - 1, line_last)
end
```

You can call this function as follows: `lua _G.highstr_highlight_remove_all()`

Cheers for the great plugin !

**Comment by kdav5758** [comment]
Done: https://github.com/kdav5758/HighStr.nvim#-notices
