### ISSUE TITLE
"Lua ver. >= 5.3" in readme must be wrong

### ISSUE THREAD

**Issue by bfredl** [kdav5758/HighStr.nvim#3]
neovim 0.5 only builds with lua 5.1 or compatible (i e luajit 2.1 ). Can probably remove the line completely as it is also impossible to build neovim 0.5 without lua 5.1 or luajit.

**Comment by kdav5758** [comment]
Oh sorry, I copy and pasted the README.md [from this other plugin of mine](https://github.com/kdav5758/TrueZen.nvim) and just replaced stuff. This requirement is real for that plugin, but not for this one. I'll remove it now.

Thanks! :)

**Comment by kdav5758** [comment]
[Done](https://github.com/kdav5758/HighStr.nvim#prerequisites)
